BOARD_TAG    = nano328
ARDUINO_PORT = /dev/ttyUSB1
ARDUINO_LIBS = OneWire DallasTemperature SoftwareSerial Time

AVRDUDE_ARD_BAUDRATE =  57600

ARDUINO_DIR  = /usr/share/arduino

include $(ARDUINO_DIR)/Arduino.mk

doxygen:
	doxygen kolibri.doxy

