BOARD_TAG    = uno
ARDUINO_PORT = /dev/ttyACM0
ARDUINO_LIBS = DHT.h

AVRDUDE_ARD_BAUDRATE = 9600

ARDUINO_DIR  = /usr/share/arduino

include $(ARDUINO_DIR)/Arduino.mk

doxygen:
	doxygen kolibri.doxy

